<h1 style = "font-size: 35px; text-align: center;">AI Genetic Hands On</h1>
<h1 style = "font-size: 25px; text-align: center;">Hospital Job Scheduling for Doctors</h1>
<h1 style = "font-size: 25px; text-align: center; color: #666">Taha Shabani - Soheil Shirvani</h1>
<h4 style="text-align: center">Spring 1400</h4>

In [1]:
testFile = "test1.txt"

In [2]:
class DayShifts:
    def __init__(self, morningReqs, eveningReqs, nightReqs):
        self.morningReqs = morningReqs
        self.eveningReqs = eveningReqs
        self.nightReqs = nightReqs
        
    def printInfo(self):
        print("morning: ", self.morningReqs, "evening: ", self.eveningReqs, "night: ", self.nightReqs,)

In [3]:
def readInput() :
    file = open(testFile, 'r+')
    fileList = file.readlines()
    fileList = [s.replace('\n', '') for s in fileList]
    
    [days, doctors] = [int(i) for i in fileList[0].split()]
    maxCapacity = int(fileList[1])
    offDays = int(fileList[2])
    
    allShifts = []
    for i in range(3, days + 3):
        dayRequirements = fileList[i].split()
        morningReqs = [int(i) for i in dayRequirements[0].split(",")]
        eveningReqs = [int(i) for i in dayRequirements[1].split(",")]
        nightReqs = [int(i) for i in dayRequirements[2].split(",")]
        allShifts.append(DayShifts(morningReqs, eveningReqs, nightReqs))
        
#     print(days, doctors, maxCapacity, offDays)
#     for i in allShifts:
#         print(i.printInfo())

    file.close()
    return [days, doctors, maxCapacity, offDays, allShifts];

In [4]:
class JobScheduler:
    def __init__(self, fileInfo):
        self.days = fileInfo[0]
        self.doctors = fileInfo[1]
        self.maxCapacity = fileInfo[2]
        self.offDays = fileInfo[3]
        self.allShifts = fileInfo[4]
        
        self.restartLimitation = 120 #consideration: if we stuck in local maximums this would be needed
        self.popSize = 500
        self.crossoverPoints = 5
        self.elitismPercentage = 10 #move x% best of parents directly to the new population
        self.pc = 0.65 #crossover probability
        self.pm = 0.2  #mutation probability
        
        self.chromosomeSet = {}
        self.chromosomes = self.getInitialChromosomes() #[0]: chromosome value, [1]: fitness value
    
    def getInitialChromosomes(self):
        print()
        # todo
    
    def schedule(self):
        print()
        # todo
        

In [5]:
import time

fileInfo = readInput()
scheduler = JobScheduler(fileInfo)

start = time.time()
scheduler.schedule()
end = time.time()

print("time: ", '%.2f'%(end - start), 'sec')



time:  0.00 sec


# Read Input File

Rows:
<table>
    <th>Number of Days</th>
    <th>Number of Doctors</th>
    <th>Maximum Shift Number</th>
    <th>Number of off-shifts</th>
    <th>each day shifts min-max</th>
</table>

In [6]:
def readInput() :
    file = open(testFile, 'r+')
    fileList = file.readlines()
    fileList = [s.replace('\n', '') for s in fileList]
    
    [days, doctors] = [int(i) for i in fileList[0].split()]
    maxCapacity = int(fileList[1])
    offDays = int(fileList[2])
    
    allShifts = []
    for i in range(3, days + 3):
        dayRequirements = fileList[i].split()
        morningReqs = [int(i) for i in dayRequirements[0].split(",")]
        eveningReqs = [int(i) for i in dayRequirements[1].split(",")]
        nightReqs = [int(i) for i in dayRequirements[2].split(",")]
        
        allShifts.append((morningReqs, eveningReqs, nightReqs))
        
#     print(days, doctors, maxCapacity, offDays)
#     for i in allShifts:
#         print(i.printInfo())

    file.close()
    return [days, list(range(doctors)), maxCapacity, offDays, allShifts];

In [7]:
days, doctors_id, maxCapacity, offDays, allShifts = readInput()

days, doctors_id, maxCapacity, offDays, allShifts

(7,
 [0, 1, 2, 3, 4],
 8,
 2,
 [([2, 3], [1, 4], [2, 2]),
  ([1, 3], [1, 2], [3, 5]),
  ([3, 3], [2, 3], [1, 4]),
  ([1, 4], [1, 2], [1, 3]),
  ([1, 1], [0, 2], [2, 4]),
  ([4, 5], [1, 2], [1, 2]),
  ([1, 3], [1, 3], [2, 2])])

# Initial Chromosomes

In [22]:
import numpy as np
from random import randrange
from random import sample

doctors = len(doctors_id)
def create_chromosome():
    chromosome = np.zeros(shape=(len(allShifts),3)).astype(int)
    print(chromosome)
    all_shift_ids = [[0 for i in range(3)] for j in range(len(allShifts))]

    for day in range(len(allShifts)):
#         print(chromosome)
        threshold = 0

        for shift in range(3):
            chromosome[day][shift] = allShifts[day][shift][0]
            threshold += (allShifts[day][shift][1] - allShifts[day][shift][0])
        
        i = 0
        randThreshold = randrange(threshold + 1)
        print (threshold, randthreshold)
        while sum(chromosome[day]) < doctors and i <= 5:
            shift_num = np.random.randint(3)
            if chromosome[day][shift_num] <= allShifts[day][shift_num][1]:
                chromosome[day][shift_num] = chromosome[day][shift_num] + 1
            i = i + 1

        all_shift_ids[day][0] = sample(doctors_id, chromosome[day][0])
        all_shift_ids[day][1] = sample(doctors_id, chromosome[day][1])
        all_shift_ids[day][2] = sample(doctors_id, chromosome[day][2])
        
    print(chromosome)
    return all_shift_ids
create_chromosome()

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
4 0
5 0
4 0
6 4
4 2
3 2
4 0
[[2 1 2]
 [1 1 3]
 [3 2 1]
 [2 1 2]
 [2 1 2]
 [4 1 1]
 [2 1 2]]


[[[4, 3], [3], [0, 4]],
 [[2], [2], [3, 1, 2]],
 [[3, 0, 1], [2, 0], [3]],
 [[4, 2], [3], [4, 1]],
 [[1, 4], [0], [2, 3]],
 [[3, 4, 1, 0], [1], [3]],
 [[4, 2], [3], [1, 4]]]

# Initial Population

In [ ]:
population_number = 50
population = []
for i in range(population_number):
    population.append(create_chromosome())
    
population

# Cross Over

In [ ]:
cross_over_chance = 0.6
cross_over_percentage = 0.8

def cross_over(chrome1, chrome2):
    # days_to_change = sorted(random.sample(range(len(allShifts)), days_to_cross_over))

#     chrome1 = population[0]
#     chrome2 = population[1]

#     display(chrome1)

    for i in range(len(allShifts)):
        if random.uniform(0, 1) >= cross_over_chance:
            temp = chrome1[i]
            chrome1[i] = chrome2[i]
            chrome2[i] = temp
        
#     display(chrome1)
    return chrome1, chrome2

cross_over(population[0], population[1])

# mutation

In [ ]:
mutation_chance = 0.2

chrome1 = population[0]
display(chrome1)
for day in range(len(allShifts)):
    for shift in range(3):
        for doctor in range(len(chrome1[day][shift])):
            if random.uniform(0, 1) >= mutation_chance:
                chrome1[day][shift][doctor] = np.random.randint(len(doctors_id))
chrome1